services:
  backend:
    image: alexmatter/theclub:backend
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "127.0.0.1:8090:8090"
    volumes:
      - ./backend/pb_data:/pb/pb_data

  web:
    image: alexmatter/theclub:web
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - ORIGIN=https://admin.guestin.org
      - POCKETBASE_URL=https://backend.guestin.org

  clienti:
    image: alexmatter/theclub:clienti
    build:
      context: .
      dockerfile: Dockerfile_clienti
    command: ["node", "-r", "dotenv/config", "build"]
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
      - ORIGIN=https://users.guestin.org
      - POCKETBASE_URL=https://backend.guestin.org