services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb/pb_data

  web:
    build:
      context: .
      dockerfile: Dockerfile_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ORIGIN=http://guestin.org:3000
      - POCKETBASE_URL=http://guestin.org:8090

  clienti:
    build:
      context: .
      dockerfile: Dockerfile_clienti
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - ORIGIN=http://guestin.org:3001
      - POCKETBASE_URL=http://guestin.org:8090