FROM oven/bun AS build

WORKDIR /app

COPY ./common ./common
COPY ./web ./web
RUN echo "ls /app" && ls /app
WORKDIR /app/web
RUN bun install
RUN bun run build
RUN echo "ls /app/web" && ls /app/web

####################
FROM node:18 AS run

ENV NODE_ENV=production

WORKDIR /app
COPY --from=build /app/web/build ./build
COPY --from=build /app/web/package.json ./package.json
COPY --from=build /app/web/node_modules ./node_modules
RUN ulimit -c unlimited
# node --env-file=.env build
CMD ["node", "-r", "dotenv/config", "build"]